### ISSUE TITLE
Error when used in an application with audit-argument-checks

### ISSUE THREAD

**Issue by firrae** [xolvio/meteor-backdoor#1]
Exception while invoking method 'xolvio/backdoor' Error: Did not check() all arguments during call to 'xolvio/backdoor'. When you have 'audit-argument-checks' installed you end up with the above error.

**Comment by ghost** [comment]
Fixed with 0.1.2

**Comment by firrae** [comment]
Thanks a bunch for the both of those @Sanjo!
