### ISSUE TITLE
Client: Uncaught ReferenceError: Npm is not defined

### ISSUE THREAD

**Issue by firrae** [xolvio/meteor-backdoor#2]
The package throws said error on the client on load even when Chimp is not running. Stack trace shows the error is from 'packages/xolvio_backdoor/server.js'.

**Comment by firrae** [comment]
Potentially this just needs to be wrapped in a Meteor.isServer check?

**Comment by ghost** [comment]
Should be fixed with 0.1.1 (https://github.com/xolvio/meteor-backdoor/commit/9b1768afd731852da590e8abe4145c50fd38e89a)
